(add-to-list 'default-frame-alist
             '(background-color . "#1d2021"))
(if (fboundp 'menu-bar-mode)
    (menu-bar-mode -1))
(if (fboundp 'tool-bar-mode)
    (tool-bar-mode -1))
(if (fboundp 'scroll-bar-mode)
    (scroll-bar-mode -1))
(if (fboundp 'fringe-mode)
    (fringe-mode 0))
